# Use root/example as user/password credentials
version: '3.1'

services:

  helloworld-was:
    image: helloworld-was:v1.0
    restart: always
    container_name: server 
    ports:
      - "3000:3000"  
    depends_on:
      - mongo
    env_file:
      - .env

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_ROOT_HOSTNAME: ${MONGO_INITDB_ROOT_HOSTNAME}