# Use root/example as user/password credentials
version: '3.1'

services:

  project2:
    image: project2_helloworld
    restart: 'always'
    container_name: server 
    ports:
      - "3000:3000"  
  mongo:
    image: mongo:5.0.17
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: jacky
      MONGO_INITDB_ROOT_PASSWORD: 12345
