name: Build and Push Docker image to ECR

on: [push]

env:
  ECR_REGISTRY: project2_helloworld
  AWS_REGION: ap-northeast-2

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ env.ECR_REGISTRY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -f path/to/Dockerfile -t project2_helloworld -t project2_helloworld:v1.1 .
          docker tag project2_helloworld $ECR_REGISTRY/project2_helloworld:latest
          docker tag project2_helloworld $ECR_REGISTRY/project2_helloworld:$IMAGE_TAG
          docker tag project2_helloworld:v1.1 $ECR_REGISTRY/project2_helloworld:v1.1
          docker push $ECR_REGISTRY/project2_helloworld:latest
          docker push $ECR_REGISTRY/project2_helloworld:$IMAGE_TAG
          docker push $ECR_REGISTRY/project2_helloworld:v1.1

